### ISSUE TITLE
Clarify implication of statement

### ISSUE THREAD

**Issue by albertrwaldron** [kimberlyahealy/Regression_2018SalesData#1]
Bullet IV - Summary: the statement on the discrepancy between the summed 2017 sales and 2017 income statement is unclear. The key takeaway is that the 2017 sales column was added in a join. As such, the difference represents the total sales to customers in 2017 who did not purchase in 2018.

**Comment by kimberlyhwaldron** [comment]
Fixed. Thank you Albert!
